### ISSUE TITLE
Instructions for local testing

### ISSUE THREAD

**Issue by robkinyon** [dawson-org/dawson-cli#157]
How would I build my application so that I can develop and test locally (without AWS)?

**Comment by lusentis** [comment]
Hi @robkinyon, the full documentation is on the way, in the meantime, you can find some details in this comment:
https://github.com/dawson-org/dawson-cli/issues/158#issuecomment-289398226

As described in such comment, AWS (and a working internet connection) is required to run the local development server too. "Local" just means that you don't have to upload/deploy your app to test changes to your code (as you would if coding directly Lambda functions, or using tools such as `apex`).

This might change in the future, maybe.

Thanks for your feedback,
