### ISSUE TITLE
API Gateway "Missing authentication token" and missing method

### ISSUE THREAD

**Issue by azappa** [dawson-org/dawson-cli#166]
```javascript
service.api = {
  path: '{lang}/service/{uid}'
};
```
lambda will not be uploaded (I tried three times with `dawson deploy`). Don't know if it anything related to dawson or API Gateway (or my fault) because in the same project I have the same parameters' names in another route and related lambda was uploaded without errors 
```javascript
singleEvent.api = {
  path: '{lang}/event/{uid}'
};
```
with that everything is fine... 
Last but not least the first example runs without problems on my local machine.

**Comment by lusentis** [comment]
I've updated the title / description to make it more clear.
Hi,
I've found a bug that causes an API Gateway Method to be linked to a wrong Resource (i.e. path) when it ends with a `{param}` in braces, whose name is also used in another function's path.

I'll dig deeper asap, for now, you can just rename the last parameter `{uid}` in one of the two paths (e.g. `{uid2}`).
