### ISSUE TITLE
Is it posible to run a meteor app with dawson?

### ISSUE THREAD

**Issue by tomyo** [dawson-org/dawson-cli#167]
This looks so cool!, I wonder if it would be posible to run a meteor app with dawson...
Thanks!

**Comment by lusentis** [comment]
Hi! I have no experience at all with meteor... could you point me to an example or app that you would like to run with dawson?
Thanks,

**Comment by tomyo** [comment]
Hi, here's a meteor app example: https://github.com/meteor/todos

**Comment by lusentis** [comment]
Thank you, I'll give it a look in the next days!
