### ISSUE TITLE
How to remove all dawson resources from AWS?

### ISSUE THREAD

**Issue by ajhekman** [dawson-org/dawson-cli#171]
What needs to be done to remove a dawson installation from AWS?

**Comment by lusentis** [comment]
You will find two CloudFormation stacks (from the AWS Console). Just delete
those.

If the stack deletion fails, the Console tells you which resources need to
be deleted manually (typically S3 Buckets).

In addition, if you have deployed using a custom domain, you may want to
delete the AWS ACM Certificate.

**Comment by ajhekman** [comment]
Thanks! I suspected that was the solution, but I'm not that familiar with CloudFormation.
