### ISSUE TITLE
Minimum deployment account privileges

### ISSUE THREAD

**Issue by nateabele** [dawson-org/dawson-cli#183]
The docs recommend creating a machine user with `AdministratorAccess` privileges for deployment. This is fine for getting started, but isn't a production best practice. Would it be possible to provide a list of the minimum privileges the account actually needs to deploy (or better yet, ship a policy doc)?

Thanks.

**Comment by lusentis** [comment]
Thank you for your comment and sorry for answering so late,
I'm planning to fix this (see #159) and shipping a policy document seems a great fit.

Simone

**Comment by lusentis** [comment]
Closing as duplicate of #159
