### ISSUE TITLE
A new section containing some tutorials, articles, etc.?

### ISSUE THREAD

**Issue by hwclass** [dawson-org/dawson-cli#195]
Hi guys,

I have just started an article series about using Dawson to serve React components. This is the [first part](https://medium.com/@hwclass/aws-rendered-react-chocolate-chips-with-dawson-part-1-a-simple-service-for-serving-components-2b47a87bebab).

And what about adding a section with a title like Articles / Tutorials into the readme file?

Cheers,

Baris

**Comment by lusentis** [comment]
Wow, great!
May I just suggest updating the install command to: `npm install -g @dawson/dawson-cli` (just add the @dawson/ scope)?

Should you need any help just reach me here or on Twitter [@Lanzone31](https://twitter.com/lanzone31). Any feedback about dawson is always appreciated!

I've updated the README.md to include the section you suggested.

Thank you!
Simone

**Comment by hwclass** [comment]
You're welome and great! I'm updating the article.

Thank you very much, @lusentis. I will ping you when I need some help.

Cheers

Baris
