### ISSUE TITLE
Add support for "singleton" resources 

### ISSUE THREAD

**Issue by lusentis** [dawson-org/dawson-cli#25]
We may want to deploy just a single resource common to all stages, for example a database instance or an ES service. The main reason would be cost saving in development. 

A possible implementation would be:
1. allow users to define a processCFSupportTemplate(template) => template, with the same logic as processCFTemplate.
2. transform the support template using such function, before updating the template

we may implement the same StackPolicy logic as in the main template.

**Comment by lcasartelli** [comment]
Below 2 interesting solutions with pros and cons.

1. **Dedicated stack for each region**
Define a new stack dedicated to shared resources. The stack should be created in all regions used by your stages.
**Pros**: You do not need to change endpoints (all resources are in the same region).
**Cons**: Expensive (3 stages in 3 different regions means 3 stacks for shared resources). Using a new stack, the deployment time grows.
We excluded a dedicated command to update the shared resources stack: too complicated for the user.
2. **Add resources into _Support_ stack**
**Pros**: Using the existing stack, the deployment time remains unchanged.
**Cons**: The shared resources are created in the stack region. If you are using a different region for your stage, you should manually change the related service endpoint in the AWS SDK.

Neither solution meets our requirements.

**Comment by lusentis** [comment]
Agree. Closing for now, anyone should feel free to reopen should a new specific use case come up.
