### ISSUE TITLE
Human readable errors

### ISSUE THREAD

**Issue by lcasartelli** [dawson-org/dawson-cli#64]
- [x] missing babel-cli: If you don't have babel-cli installed, dawson displays a generic error.
- [x] missing .babelrc or syntax error in api.js
- [x] proxy error when a stack does not exist (`Error getting stack outputs and resources { ValidationError: Stack with id *** does not exist...`)
- [x]  proxy error when a function has not yet been deployed
- [x] stack update fails

**Comment by lusentis** [comment]
initial implementation in 31f6068. Merging soon!

**Comment by lusentis** [comment]
further improved in 8653816
