### ISSUE TITLE
Optional SSL/TLS certificate

### ISSUE THREAD

**Issue by lcasartelli** [dawson-org/dawson-cli#70]
We may add an additional field into package.json to make _certificate creation_ an optional feature.

**Comment by lusentis** [comment]
we should add a --no-acm to skip SSL/TLS and to *not* set ViewerCertificate property on CloudFront Distribution

**Comment by lusentis** [comment]
a couple of hints if you want to contribute, starting here:
https://github.com/dawson-org/dawson-cli/blob/master/src/factories/cf_cloudfront.js#L65

The if statement should become something similar to:
```js
if (!alias || skipAcmCertificate) {
```

`skipAcmCertificate` should be passed down by `deploy.js` (https://github.com/dawson-org/dawson-cli/blob/master/src/commands/deploy.js#L224), which sets a value for this flag in the `run` method at the bottom of the file.
You should also add the `--no-acm` description to index.js in the deploy command help.

**Comment by lusentis** [comment]
just to be clear, "skipping creating a certificate" should be a temporary workaround (e.g.: you may want to perform a quick deploy / your customer is on holiday and cannot forward the approval email to you etc.).
That said, we **do want** to add a `--skip-acm` CLI option. We **do not** want to implement a config setting in the package.json.
