### ISSUE TITLE
remove noWrap, isEventHandler, keepWarm

### ISSUE THREAD

**Issue by lusentis** [dawson-org/dawson-cli#77]
- noWrap has no real use case and the distinction with isEventHandled is unclear
- isEventHandler is confusing and shall be automatically implied when specifying "path: false"; implementing Lambda Environment Variables will remove the need of calling getStackOutputs before running the function
- keepWarm does not work as expecting; cold-start is also now acceptably low since we've dropped babel-register a few releases ago

**Comment by lcasartelli** [comment]
+1

**Comment by lusentis** [comment]
*
*
* keepWarm is gone in 52c9d4bf815f7c3c44901521d9992a528578f9ce
