### ISSUE TITLE
Low speed from v.0.4+

### ISSUE THREAD

**Issue by azappa** [dawson-org/dawson-cli#82]
In latest releases, when using `dawson-cli` from localhost, speed drastically reduce (eg: when rendering a page with two api calls from online services it tooks 18seconds or more).

**Comment by lusentis** [comment]
this is an issue with docker on ubuntu.

```bash
$ docker run -it --rm lambci/lambda:build bash -c  "time curl http://www.google.com"
$ docker run -it --rm lambci/lambda:build bash -c  "time curl -4 http://www.google.com"
```
if the second command reports a time considerably faster than the first command, you may find this solution useful:
* https://askubuntu.com/questions/32298/prefer-a-ipv4-dns-lookups-before-aaaaipv6-lookups/32312#32312
* http://www.webupd8.org/2009/11/how-to-disable-ipv6-in-ubuntu-910.html
