### ISSUE TITLE
Multiple domains for cloudfront distributions

### ISSUE THREAD

**Issue by azappa** [dawson-org/dawson-cli#90]
Can I use syntax like this in my package.json?
```json
"dawson": {
    "cloudfront": {
      "prod": ["example.com", "www.example.com"]
    }
}
```

From [App Configuration](https://github.com/dawson-org/dawson-cli/wiki/App-Configuration) value for each key must be a string or boolean.

**Comment by lusentis** [comment]
Thanks, this sounds like a nice feature to have, especially for your use case.
We'll ad it to the backlog.

**Comment by lusentis** [comment]
Currently, it's pretty hard to implement, due to the way ACM Certificates are requested and handled by CloudFront. Closing this for now, feel free to add submit a PR.
